using LoESoft.AssetsManager.Core.Assets.Structure;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Linq;

namespace LoESoft.AssetsManager.Core.Structure
{
    public struct XmlData
    {
        public List<ObjectsContent> Objects { get; set; }
        public List<ItemsContent> Items { get; set; }
        public List<TilesContent> Tiles { get; set; }

        public XmlData(List<ObjectsContent> objects, List<ItemsContent> items, List<TilesContent> tiles)
        {
            Objects = objects;
            Items = items;
            Tiles = tiles;
        }

        public void ToXml()
        {
            var ids = new List<int>();

            foreach (var obj in Objects)
                ids.Add(obj.Id);

            foreach (var itm in Items)
                ids.Add(itm.Id);

            foreach (var tle in Tiles)
                ids.Add(tle.Id);

            ids.OrderBy(id => id);

            var xmls = new XDocument(
                new XDeclaration("1.0", "utf-8", "no"),
                new XComment($"This file was automatic generated by {App.Name} v{App.Version}"),
                new XComment("All rights reserved."),
                new XComment("Copyright (c) LoESoft Games 2018"),
                new XElement("Objects",
                    ids.Count == 0 ? null : "all objects, items and tiles XElements goes here"
                    )
                );
        }
    }
}