using LoESoft.AssetsManager.Core.Assets;
using LoESoft.AssetsManager.Core.Assets.Structure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Linq;
using static LoESoft.AssetsManager.Core.Assets.Structure.XmlContent;

namespace LoESoft.AssetsManager.Core.Structure
{
    public struct XmlData
    {
        public string Name { get; set; }
        public List<ObjectsContent> Objects { get; set; }
        public List<ItemsContent> Items { get; set; }
        public List<TilesContent> Tiles { get; set; }

        public XmlData(string name, List<ObjectsContent> objects, List<ItemsContent> items, List<TilesContent> tiles)
        {
            Name = name;
            Objects = objects;
            Items = items;
            Tiles = tiles;
        }

        public XDocument ToXml()
        {
            var datas = new Dictionary<int, Tuple<ContentType, object>>();

            foreach (var obj in Objects)
                datas.Add(obj.Id, new Tuple<ContentType, object>(ContentType.Objects, obj));

            foreach (var itm in Items)
                datas.Add(itm.Id, new Tuple<ContentType, object>(ContentType.Items, itm));

            foreach (var tle in Tiles)
                datas.Add(tle.Id, new Tuple<ContentType, object>(ContentType.Tiles, tle));

            var xmls = new List<XElement>();

            foreach (var data in datas.OrderBy(id => id.Key))
                switch (data.Value.Item1)
                {
                    case ContentType.Objects: xmls.Add(((ObjectsContent)data.Value.Item2).ToXml()); break;
                    case ContentType.Items: xmls.Add(((ItemsContent)data.Value.Item2).ToXml()); break;
                    case ContentType.Tiles: xmls.Add(((TilesContent)data.Value.Item2).ToXml()); break;
                }

            return new XDocument(
                new XDeclaration("1.0", "utf-8", "no"),
                new XComment($"\n\tXML Document: {Name}\n" +
                $"\tCreated at {DateTime.UtcNow.ToString("MM/dd/yyyy hh:mm:ss")}\n\n" +
                $"\tThis file was automatically generated by {App.Name} v{App.Version}.\n" +
                $"\tAll rights reserved.\n" +
                $"\tCopyright (c) LoESoft Games 2018\n"),
                new XElement("Objects",
                    xmls.Count == 0 ? null : xmls
                    )
                );
        }
    }
}